import { 
  mdiClose, 
  mdiHome, 
  mdiEyeOff, 
  mdiEye, 
  mdiMagnify, 
  mdiAccount, 
  mdiAccountOutline,
  mdiLockOutline,
  mdiAccountSearch, 
  mdiChevronRight, 
  mdiCalendarClock, 
  mdiPhoneOutline, 
  mdiAccountCircle, 
  mdiPencilOutline,
  mdiAccountOffOutline,
  mdiAlertCircleOutline,
  mdiRefresh,
  mdiPlus,
  mdiFileExcel,
  mdiDeleteOutline,
  mdiFormatListBulleted
} from '@mdi/js';

export const icons = {
  close: mdiClose,
  home: mdiHome,
  eyeOff: mdiEyeOff,
  eye: mdiEye,
  magnify: mdiMagnify,
  account: mdiAccount,
  accountOutline: mdiAccountOutline,
  lockOutline: mdiLockOutline,
  accountSearch: mdiAccountSearch,
  chevronRight: mdiChevronRight,
  calendarClock: mdiCalendarClock,
  phoneOutline: mdiPhoneOutline,
  accountCircle: mdiAccountCircle,
  pencilOutline: mdiPencilOutline,
  accountOffOutline: mdiAccountOffOutline,
  alertCircleOutline: mdiAlertCircleOutline,
  refresh: mdiRefresh,
  plus: mdiPlus,
  fileExcel: mdiFileExcel,
  deleteOutline: mdiDeleteOutline,
  formatListBulleted: mdiFormatListBulleted
};
